# Matrix

## Creating Matrix object

`Matrix` objects can be created in several ways.

```cpp
// Create a Matrix object equivalent to
// m <- matrix(0, nrow=2, ncol=2)
NumericMatrix m1( 2 );

// m <- matrix(0, nrow=2, ncol=3)
NumericMatrix m2( 2 , 3 );

// m <- matrix(v, nrow=2, ncol=3)
NumericMatrix m3( 2 , 3 , v.begin() );
```

In addition, a matrix object in R is actually a vector that the number of rows and columns is set in the attribute `dim`. Thus, if you create a vector with the attribute `dim` in Rcpp and return it to R, it will be treated as a matrix.


```cpp
// [[Rcpp::export]]
NumericVector rcpp_matrix(){
    // Creating a vector object
    NumericVector v = {1,2,3,4};

    // Set the number of rows and columns to attribute dim of the vector object.
    v.attr("dim") = Dimension(2, 2);

    // Return the vector to R
    return v;
}
```

Execution result

```
> rcpp_matrix()
     [,1] [,2]
[1,]    1    3
[2,]    2    4
```

Please note that even if you set a value to the `dim` attribute of a `Vector` object, the type of the object remains a `Vector` type in the Rcpp code. Thus, if you want to convert the type into `Matrix` type in Rcpp, you need to use `as<T>()` function.

```cpp
// Set number of rows and columns to attribute dim
v.attr("dim") = Dimension(2, 2);

// Converting to Rcpp Matrix type
NumericMatrix m = as<NumericMatrix>(v);
```

## Accessing to Matrix elements

Using the `()` operator, you can get from and assign to the values of elements of a `Matrix` object by specifying its column number and row number. As in vectors, row numbers and column numbers in `Matrix` start with 0. If you want to access a specific row or column, use the symbol `_`.

You can also use the `[]` operator to access an element as a vector connecting the columns of a matrix.



```cpp
// Creating a 5x5 numerical matrix
NumericMatrix m( 5, 5 );

// Retrieving the element of row 0 and column 2
double x = m( 0 , 2 );

// Copying the value of row 0 to the vector v
NumericVector v = m( 0 , _ );

// Copying the value of column 2 to the vector v
NumericVector v = m( _ , 2 );

// Copying the row (0 to 1) and column (2 to 3) to the matrix m2
NumericMatrix m2 = m( Range(0,1) , Range(2,3) );

// Accessing matrix element as vector
m[5]; // This points to the same element as m(0,1)
```


### Accessing as a reference to row, column, and submatrix

Rcpp also provides types that hold "references" to specific parts of a matrix.

```cpp
NumericMatrix::Column col = m( _ , 1);  // Reference to the column 1
NumericMatrix::Row    row = m( 1 , _ ); // Reference to the row 1
NumericMatrix::Sub    sub = m( Range(0,1) , Range(2,3) ); // Reference to sub matrix
```
Assigning a value to a "reference" object of a matrix is equivalent to assigning the value to its original matrix. For example, assigning a value to `col` will assign a value to column 1 of `m`.

```cpp
// Reference to the column 1
NumericMatrix::Column col = m( _ , 1);  

// The value of the column 1 of matrix m will be doubled
col = 2 * col;

// Synonymous with the above example
m( _ , 1) = 2 * m( _ , 1 );
```




## Member functions {#member-functions-matrix}

Since `Matrix` is actually `Vector`, `Matrix` basically has the same member functions as `Vector`. Thus, member functions unique to `Matrix` are only presented below.

### nrow() rows()

Returns the number of rows.

### ncol()　cols()

Returns the number of columns.

### row( i )

Return a reference `Vector::Row` to the `i`th　row.

### column( i )

Return a reference `Vector::Column` to the `i`th　column.

### fill_diag( x )

Fill diagonal elements with scalar value `x`.

### offset( i, j )

Returns the numerical index in the original vector of the matrix corresponding to the element of row `i` and column `j`.



## Static member functions {#static-member-functions-matrix}

`Matrix` basically has the same static member function as `Vector`. The static member functions unique to `Matrix` are shown below.

### Matrix::diag( size, x )

Returns a diagonal matrix whose number of rows and columns equals to "size" and the value of the diagonal element is "x".



## Other functions related to Matrix

This section shows functions relating to the `Matrix`.

### rownames( m )

Get and set the row name of matrix m.

```
CharacterVector ch = rownames(m);
rownames(m) = ch;
```

### colnames( m )

Get and set the column name of matrix m.

```
CharacterVector ch = colnames(m);
colnames(m) = ch;
```


### transpose( m )

Return the transposed matrix of matrix `m`.
